### ISSUE TITLE
Website Copy Sprint

### ISSUE THREAD

**Issue by exeunt3** [HPGF-Ecosystem-Support-Machine/metamachine#26]
@MaxWolfard  and @exeunt3 begin to generate copy to fill in the website page frames made by @oovg

**Comment by TravisWyche** [comment]
@exeunt3 Please add a description? I think this is overlapping with #7 and is already underway. If not, let's distinguish between them.

**Comment by TravisWyche** [comment]
Redundant with #7. Closed.
